export const CREATE_USER = "CREATE_USER";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_TODO_SUCCESS = "LOAD_TODO_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
